site_name: Sharded
site_url: https://docs.sharded.app/

site_description: >
  Sharded is a python powered discord bot that powers your server with
  advanced moderation, customization, and self-hosted features.

repo_name: shardedinteractive/sharded
repo_url: https://github.com/shardedinteractive/sharded

nav:
  - Home:
    - "Welcome to Sharded" : index.md
    - "Self-Hosting Sharded":
        - "Getting Started": getting-started.md
        - "Basic Configuration": basic.md
    - "Sharded Programs":
      - "Sharded Verification": verification.md
  - Addons:
    - addons/index.md
  - Blog:
    - blog/index.md

theme:
  name: material

  palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode

      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: "#4a96d3"
        accent: "#8ecae6"
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: "#8ecae6"
        toggle:
          icon: material/brightness-4
          name: Switch to system preference
  font:
    text: "Roboto"
    code: " JetBrains Mono"

  logo: "assets/sharded_transparent.png"
  favicon: "assets/favicon.ico"

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - privacy
  - search
  - blog
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - git-committers:
      enabled: !ENV [CI, false]
      repository: shardedinteractive/docs
      branch: main

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - attr_list
  - def_list
  - admonition
  - md_in_html

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
  analytics:
    provider: google
    property: G-6SBXSR62C1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            
            
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/ShardedInteractive/sharded/issues/new?template=feedback.yml" target="_blank" rel="noopener">feedback form</a>.

copyright: >
  Copyright &copy; 2024 - 2025 Sharded Interactive –
  <a href="#__consent">Change cookie settings</a>

extra_css:
  - stylesheets/extra.css